//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.26 at 11:08:39 AM CET 
//


package se.kth.ns.jobservicecompany;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the se.kth.ns.jobservicecompany package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: se.kth.ns.jobservicecompany
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Cv }
     * 
     */
    public Cv createCv() {
        return new Cv();
    }

    /**
     * Create an instance of {@link Transcript }
     * 
     */
    public Transcript createTranscript() {
        return new Transcript();
    }

    /**
     * Create an instance of {@link EmploymentRecord }
     * 
     */
    public EmploymentRecord createEmploymentRecord() {
        return new EmploymentRecord();
    }

    /**
     * Create an instance of {@link Profile }
     * 
     */
    public Profile createProfile() {
        return new Profile();
    }

    /**
     * Create an instance of {@link Company }
     * 
     */
    public Company createCompany() {
        return new Company();
    }

    /**
     * Create an instance of {@link Cv.Projects }
     * 
     */
    public Cv.Projects createCvProjects() {
        return new Cv.Projects();
    }

    /**
     * Create an instance of {@link Transcript.Projects }
     * 
     */
    public Transcript.Projects createTranscriptProjects() {
        return new Transcript.Projects();
    }

    /**
     * Create an instance of {@link EmploymentRecord.Projects }
     * 
     */
    public EmploymentRecord.Projects createEmploymentRecordProjects() {
        return new EmploymentRecord.Projects();
    }

    /**
     * Create an instance of {@link Profile.Projects }
     * 
     */
    public Profile.Projects createProfileProjects() {
        return new Profile.Projects();
    }

    /**
     * Create an instance of {@link Company.Office }
     * 
     */
    public Company.Office createCompanyOffice() {
        return new Company.Office();
    }

}
