//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.28 at 11:04:26 AM CET 
//


package se.kth.ns.jobservicecompany;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the se.kth.ns.jobservicecompany package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: se.kth.ns.jobservicecompany
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Cv }
     * 
     */
    public Cv createCv() {
        return new Cv();
    }

    /**
     * Create an instance of {@link Transcript }
     * 
     */
    public Transcript createTranscript() {
        return new Transcript();
    }

    /**
     * Create an instance of {@link EmploymentRecord }
     * 
     */
    public EmploymentRecord createEmploymentRecord() {
        return new EmploymentRecord();
    }

    /**
     * Create an instance of {@link Profile }
     * 
     */
    public Profile createProfile() {
        return new Profile();
    }

    /**
     * Create an instance of {@link Company }
     * 
     */
    public Company createCompany() {
        return new Company();
    }

    /**
     * Create an instance of {@link Profile.University }
     * 
     */
    public Profile.University createProfileUniversity() {
        return new Profile.University();
    }

    /**
     * Create an instance of {@link Profile.Position }
     * 
     */
    public Profile.Position createProfilePosition() {
        return new Profile.Position();
    }

    /**
     * Create an instance of {@link Transcript.University }
     * 
     */
    public Transcript.University createTranscriptUniversity() {
        return new Transcript.University();
    }

    /**
     * Create an instance of {@link Cv.Project }
     * 
     */
    public Cv.Project createCvProject() {
        return new Cv.Project();
    }

    /**
     * Create an instance of {@link EmploymentRecord.Position }
     * 
     */
    public EmploymentRecord.Position createEmploymentRecordPosition() {
        return new EmploymentRecord.Position();
    }

    /**
     * Create an instance of {@link Profile.Project }
     * 
     */
    public Profile.Project createProfileProject() {
        return new Profile.Project();
    }

    /**
     * Create an instance of {@link Company.Office }
     * 
     */
    public Company.Office createCompanyOffice() {
        return new Company.Office();
    }

    /**
     * Create an instance of {@link Profile.University.Course }
     * 
     */
    public Profile.University.Course createProfileUniversityCourse() {
        return new Profile.University.Course();
    }

    /**
     * Create an instance of {@link Profile.Position.Office }
     * 
     */
    public Profile.Position.Office createProfilePositionOffice() {
        return new Profile.Position.Office();
    }

    /**
     * Create an instance of {@link Transcript.University.Course }
     * 
     */
    public Transcript.University.Course createTranscriptUniversityCourse() {
        return new Transcript.University.Course();
    }

}
